# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/nexusdev
spring.datasource.username=nexus_admin
spring.datasource.password=soman503
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Server port
server.port=8080

# App name
spring.application.name=NexusDev
